#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
require 'clive'

options = {}
c = Clive.new do

  switch :v, :verbose, "Run verbosely" do
    options[:verbose] = true
  end
  
  flag :t, :type, "TYPE", "Change type to TYPE" do |i|
    options[:type] = i
  end
  
  flag(:long_only, "A flag with only a long") {}
  
  flag :p, :print, "[TEXT]", "Print TEXT, defaults to 'hey'" do |i|
    i ||= 'hey'
    p i
  end
  
  flag(:z, :apple, "More applez") {}
  
  command :add, "Add something" do
    
    header "Usage: bin_test add [options]\n" +
           "Use add to add things to add, which in turn can be added."
    
    switch :f, :full, "Use full" do
      options[:full] = true
    end
    
    # Use with app-name add -e
    switch :e, :empty, "Use empty" do
      options[:full] = false
    end
    
    footer "If the header was a little confusing, don't worry the footer thought so too."
  
  end
  
  command :remove, :delete, "Get rid of something" do
    switch :f, :force, "Force" do
      p "deleting! now"
    end
  end
  
  
  option_missing do |name|
    puts "hi, #{name}"
  end

end

p ARGV
p c.parse(ARGV)
p options

